language: node_js
node_js:
- '0.10'
notifications:
  slack:
    secure: LsUTcvgSxwh2AuOxQDlhLmJs2NVWKNXiSCryoDREc4hbTTU0jvAVZLveHA6xzYV8LbZzpKvluc7n2MY7SMwdpFQGDtmKJIvexgnBhz1viOFGoCuhbRETvgiemgvZM202sM17OME8WT/7KqKRWpU8RSNOBCp5EFxE7MzzVhf/bZ0=
