language: node_js
node_js:
- '0.10'
notifications:
  slack:
    secure: RXPfDgok0zXtSKFmQuAwr4QBBqFo0xeRgmHyRFFes5ZeiX+6wjiSZSGveAt+56xq7883kq0Nqa9+VMun4Grjzq8VcCx5qlVVuy5USNXmvZI9hRsOpwnkmMoa6dHeQoa+njTVBOMtvhtfOfRYk3VKbF+N9TDVJC1fyUVshX8kRNU=
